/*estan
FUNCIÓN QUE RECIBA COMO PARÁMETROS DOS NÚMEROS Y UN ARRAY DE 
20 NUMEROS, Y DEVUELVA EL VALOR VERDADERO (true) SI AMBOS
NUMEROS ESTÁN EN EL ARRAY, Y FALSO (false) EN CASO CONTRARIO.

llenar
FUNCIÓN QUE RECIBA UN ARRAY DE 20 ELEMENTOS Y LO LLENE CON
NUMEROS ALEATORIOS ENTRE 1 Y 100.

mostrar
FUNCIÓN QUE RECIBA UN ARRAY DE 20 ELEMENTOS Y LO MUESTRE POR 
PANTALLA

programa principal
PROGRAMA QUE TIENE UN ARRAY DE 20 ELEMENTOS (vacio??). MEDIANTE 
LLAMADAS A LAS FUNCIONES ANTERIORES: LLENA EL ARRAY, LO MUESTRA 
POR PANTALLA, PIDE DOS NUMEROS POR TECLADO Y NOS DICE SI LOS
DOS NUMEROS ESTÁN EN EL ARRAY O NO.
*/

#include <stdio.h>

bool estan(int num1, int num2, int numeros[20]){
     int aux;
     bool num;
     
     
}
